# Generated by Django 4.1.7 on 2023-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profilePic',
            field=models.ImageField(default='2023.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(default=298944),
        ),
    ]
