# Generated by Django 4.1.7 on 2023-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_profilepic_alter_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(default=974392),
        ),
    ]
