# Generated by Django 4.1.7 on 2023-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_account_code_alter_tempuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppwd',
            name='code',
            field=models.IntegerField(default=150566),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(default=561101),
        ),
    ]
