# Generated by Django 4.1.7 on 2023-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_temppwd_code_alter_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppwd',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(default=934235),
        ),
        migrations.AlterField(
            model_name='temppwd',
            name='code',
            field=models.IntegerField(default=605703),
        ),
    ]
