# Generated by Django 4.1.7 on 2023-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_temppwd_userid_alter_account_code_alter_temppwd_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='code',
            field=models.IntegerField(default=639031),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(default=230113),
        ),
        migrations.AlterField(
            model_name='temppwd',
            name='code',
            field=models.IntegerField(default=344389),
        ),
    ]
