# Generated by Django 4.1.7 on 2023-04-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tempuser_code_alter_account_code_alter_temppwd_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppwd',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(default=807645),
        ),
        migrations.AlterField(
            model_name='temppwd',
            name='code',
            field=models.IntegerField(default=828350),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='code',
            field=models.IntegerField(default=913783),
        ),
    ]
