# Generated by Django 4.1.7 on 2023-03-08 01:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player', 'game')},
        ),
    ]
